matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "3.5"
    - os: linux
      dist: trusty
      language: python
      python: "3.6"

cache:
  pip: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python -m compileall fritz-switch-profiles/fritz-switch-profiles.py
  - flake8 fritz-switch-profiles/fritz-switch-profiles.py
  - codespell fritz-switch-profiles/fritz-switch-profiles.py

deploy:
  provider: pypi
  user: $PYPIUSER
  password: $PYPIPASSWORD
